### ISSUE TITLE
Error: There is already a collection named "users"

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/create#44]
After a fresh clone/install, I see the following error when navigating to the engine: http://localhost:4010/

```
Your app is crashing. Here's the latest log:

Started MongoDB.
ENOENT: no such file or directory, open '.env'
2020-12-22T17:43:00.961Z [unchained] info: WorkerDirector -> Registered EXTERNAL shop.unchained.worker-plugin.external@1.0 (External plugin as a placeholder for workers who interact with the system only via GraphQL) {}

You are using the default secret "secret" which is not secure.
Please change it with a strong random token.
[FilesCollection.storagePath] Set to: assets/app/uploads/avatars
/Users/schmidsi/.meteor/packages/meteor-tool/.1.11.1.116t4gt.0c4d++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: There is already a collection named "users"
    at new Collection (packages/mongo/collection.js:122:15)
    at module (packages/unchained:core-users/db/collections.js:8:22)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/schmidsi/.meteor/packages/modules/.0.15.0.pyq4ir.fh6r9++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
    at module (packages/unchained:core-users/db/schema.js:1:411)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/Users/schmidsi/.meteor/packages/modules/.0.15.0.pyq4ir.fh6r9++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
    at module (packages/unchained:core-users/users.js:1:26)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /Users/schmidsi/Development/@unchainedshop/create/engine/.meteor/local/build/programs/server/packages/unchained_core-users.js:762:15
    at /Users/schmidsi/Development/@unchainedshop/create/engine/.meteor/local/build/programs/server/packages/unchained_core-users.js:767:3
    at /Users/schmidsi/Development/@unchainedshop/create/engine/.meteor/local/build/programs/server/boot.js:401:38
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by pozylon** [comment]
The cause is when you have meteor accounts in your project and use the newest unchained version. See the changelog. meteor remove accounts accounts-base accounts-password
